Update to DB Writer Common 4.0
keboola/db-writer-mssql pull request #22
Opened 2018-05-03 12:21 UTC by MiroCillik

- Update to DB Writer Common 4.0 (https://github.com/keboola/db-writer-common)
- Tests are therefore slightly reworked
- SSH keys are generated using script from DB Writer Common lib

2018-05-03 14:23 UTC, tomasfejfar requested changes

2018-05-03 14:23 UTC, tomasfejfar commented on .travis.yml
> +  - docker-compose run tests
nestačí tady, kdyby ten wait byl v "links"?

2018-05-03 14:23 UTC, tomasfejfar commented on .travis.yml
> +  - source ./vendor/keboola/db-writer-common/tests/generate-ssh-keys.sh
šlo by prosím  tohle celé okomentovat? Vůbec nevím, proč to musí být zrovna takhle. A proč tam musí být compose down?  :(

2018-05-03 14:23 UTC, tomasfejfar commented on .travis.yml
> +  - docker-compose run tests
err... v depends_on

2018-05-03 14:23 UTC, tomasfejfar commented on .travis.yml
> +  - docker-compose run --rm app composer install -n
proč se tady spustí app a ne tests?

2018-05-03 14:23 UTC, tomasfejfar commented on tests/phpunit/Writer/MSSQLSSHTest.php
> +    protected $dataDir = __DIR__ . "/../../data";
když je tady tohle, tak by se to mělo použít na začátku setUp, ne?

2018-05-03 14:23 UTC, tomasfejfar commented on tests/phpunit/Writer/MSSQLSSHTest.php
>          if (!is_dir('/data')) {
tady

2018-05-03 14:23 UTC, tomasfejfar commented on tests/phpunit/Writer/MSSQLTest.php
>          if (!is_dir('/data')) {
použít `$dataDir`?

2018-05-03 14:27 UTC, tomasfejfar commented
Mimochodem, tady zase platí, že ten PR kombinuje naprosto nesouvisející věci :/ Mohly to být tři oddělené PR a některé z nich se mohly mergnout rovnou. 

Resp. možná to nějak souvisí a já to jen nevím (tak se omlouvám), ale to SSH (a s tím související změny v dockeru a buildu) mi přijde jako úplně oddělená změna, která by měla mít vlastní PR.

2018-05-03 14:32 UTC, MiroCillik commented on .travis.yml
> +  - docker-compose run tests
Nestaci, nefungovalo mi to tak

2018-05-03 14:34 UTC, MiroCillik commented on .travis.yml
> +  - docker-compose run --rm app composer install -n
Pretoze app ma namapovany ten volume. Takze takto sa mi nainstaluju veci do `/vendors`. A odtial sa potom spusti ten skript, ktory vygeneruje tie SSH kluce. Je to trochu zamotanejsie ako som zamyslal :)

2018-05-03 14:34 UTC, MiroCillik commented on tests/phpunit/Writer/MSSQLTest.php
>          if (!is_dir('/data')) {
Jop, to mas pravdu. To tam ostalo z nejakeho hotfixu.

2018-05-03 14:35 UTC, MiroCillik commented
Vsechno to souvisi s tym updatom na wr-db-common 4.0. Takze preto je to tak :/

2018-05-03 14:38 UTC, MiroCillik commented on .travis.yml
> +  - source ./vendor/keboola/db-writer-common/tests/generate-ssh-keys.sh
Musim pustit composer z `app`, pretoze app ma namapovany volume, takze sa mi nahraju veci do `vendors`. Z `vendors` potom pustim skript na generovanie klucov.
A `docker-compose down` je tam preto, ze ten `app` ma nalinkovany `sshproxy` kontajner, takze ho spusti, ale ten kontajner este nema nastaveny SSH klic :) Takze ho potrebujem vypnut, vygnerovat klice a pak sa spusti spravne spolu s testami. 

Trochu som to nedomyslel s tym generovanim klucov :/

2018-05-03 14:48 UTC, Halama commented on .travis.yml
> +  - docker-compose run --rm app composer install -n
Nebo to můžeš udělat stejně jako to děláme u nových appek. Tzn. docker-compose je jen pro dev a v ci se to nasetupuje bez něj. Např. https://github.com/keboola/db-extractor-impala/blob/master/.travis.yml

2018-05-03 15:32 UTC, tomasfejfar commented on .travis.yml
> +  - docker-compose run --rm app composer install -n
Tak to mi tady zrovna přijde ten compose lepší. Konec konců je k tomu určený (na orchestraci víc kontejnerů).

2018-05-03 15:32 UTC, tomasfejfar commented on .travis.yml
> +  - docker-compose run --rm app composer install -n
Ale mohlo by to jen zbuildnout ten app a zavolat na něm composer install. To by mohlo...

2018-05-03 16:03 UTC, tomasfejfar commented on .travis.yml
> +  - docker-compose run --rm app composer install -n
Tohle jsem vyřešil buildem čistě toho kontejneru. Tím pádem je to o něco jednodušší.

2018-05-03 16:08 UTC, tomasfejfar commented on .travis.yml
> +  - docker-compose run tests
Myslím, že to funguje. 

Principielně to funguje takto:

* Máme appku a služby (mysql, sshproxy). 
* pro každou službu je kontejner "*-ready", který má nastavené, že čeká, až se služba spustí. V `links` má tu službu. 
* služba nemá žádné další závislosti, pokud je skutečně nemá (nepotřebuje je ke spuštění)
* appka má `depends_on` na `*-ready`

Ve chvíli, kdy se má appka spustit, tak:
* Se zjistí, že nejdřív musí běžet `mssql-ready` a `sshproxy-ready`
* spustí se `mssql-ready` a `sshproxy-ready`, které linkují svoje servicy a jsou blokované, dokud nejsou servicy hotové a neodpovídají
* spustí se servicy
* odblokují se `*-ready`
* může se sputit kontejner appky

2018-05-03 16:10 UTC, tomasfejfar commented
Jasně, teď už to chápu, proč to všechno souvisí se vším. 

Pushnul jsem nějaké úpravy. Trochu navíc je tam optimalizace Dockerfile, ale to jsem potřeboval, protože jsem furt dokola buildoval lokálně a hrozně to trvalo. Takže by to ještě měl reviewnout někdo další.

2018-05-03 19:48 UTC, Halama commented on .travis.yml
> +  - docker-compose run tests
Myslím si že tohle fungovat nebude. 

Provede to tohle:
- spustí `mssql` a `ssh-proxy`
- spustí `mssql-ready` a `sshproxy-ready` ty se nahodí a čekají na ty porty a potom co jsou porty dostupné nebo dojde k timeoutu se vypnou.
- spustí se kontejner appky úplně nezávisle na běžících `*-ready` kontejnerech. Spustí se v moment kdy `*-ready` kontejnery nastartují, ne kdy doběhnou.

Jde to vidět např. na tom `sshproxy-ready` který má špatný port (má mít interní v docker síti `22`) a timeoutuje po 2 minutách. Pokud by to fungovalo tak jak píšeš tak se to celé spustí až po tech dvou minutách.

![image](https://user-images.githubusercontent.com/903531/39599280-a233a422-4f1b-11e8-9209-6970401211ab.png)

2018-05-04 06:37 UTC, MiroCillik commented
Ok, vyzera to dobre. Este by som mozne tie `mysql-ready` a `sshproxy-ready` spojil do jednej definicie.

2018-05-04 06:39 UTC, MiroCillik commented
Aha, vsimol som si Martinov koment, tak ja to este vyskusam.

2018-05-04 07:37 UTC, MiroCillik commented on .travis.yml
> +  - docker-compose run tests
@Halama na travise to ale preslo v poriadku. Moze to byt nahoda ale nemyslim si :) 
Tie `*-ready` kontajnery nemusia mat ziadne porty si myslim. Ten hlavny `app` alebo `tests` kontajner sa nepripojuje na tieto `*-ready` kontajnery. To ze ich ma v `depends_on` len hovori, ze na ne musi pockat a oni blokuju dovtedy, kym nie su dostupne tie ich nalinkovane sluzby (sshproxy a mssql).
Ten hlavny kontajner (app, tests) sa pripaja normalne na `sshproxy` a `mssql` (nie na tie `*-ready`). Tie maju porty spravne ako vidiet z tvojho screenu. Nemusi ich mat v `depends_on` (alebo `links`) pretoze pre vsetky servisi z toho compose suboru je vytvorena jedna siet a vsetky sa navzajom vidia (ak tomu spravne rozumiem).
S tym poradim mas pravdu ale, este to vyskusam.

2018-05-04 07:39 UTC, Halama commented on .travis.yml
> +  - docker-compose run tests
se podivej treba na ten `sshproxy-ready` ten se vubec nedocka protoze ma spatne port.

2018-05-04 07:41 UTC, Halama commented on .travis.yml
> +  - docker-compose run tests
`depends_on` nic neblokuji, jenom to nastartuje ty kontejnery jako první. To že to prošlo na travisu je náhoda.

2018-05-04 07:46 UTC, Halama commented on .travis.yml
> +  - docker-compose run tests
co se týče toho portu tak ty tam máš `sshproxy:1422` a pod ním nic není. Musí tam být `sshproxy:22`. Jinak je pravda že ty `links` se můžou vyhodit https://docs.docker.com/compose/compose-file/#links asi.

2018-05-04 08:07 UTC, Halama commented on .travis.yml
> +  - docker run -v $(pwd):/code app composer install --prefer-dist --no-interaction
k čemu tady je tenhle build? se to buildne a pak se to nikde nepoužije.

2018-05-04 08:10 UTC, MiroCillik commented
To je kvoli tomu, aby sa do vendors nainstalovala ta common knihovna a z
nej sa potom spusti ten skript na generovanie ssh klucov

On Fri, 4 May 2018 10:07 Martin Halamíček, <notifications@github.com> wrote:

> *@Halama* commented on this pull request.
> ------------------------------
>
> In .travis.yml
> <https://github.com/keboola/db-writer-mssql/pull/22#discussion_r186012915>
> :
>
> > @@ -6,10 +6,12 @@ services:
>    - docker
>
>  install:
> -  - docker-compose build tests
> +  - docker build -t app .
> +  - docker run -v $(pwd):/code app composer install --prefer-dist --no-interaction
>
> k čemu tady je tenhle build? se to buildne a pak se to nikde nepoužije.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/keboola/db-writer-mssql/pull/22#pullrequestreview-117519944>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABa0j0rVP5g_ntNLV6ddfOzm0caR-6g1ks5tvAw5gaJpZM4Tw-uY>
> .
>

2018-05-04 08:12 UTC, Halama commented
omg:)

2018-05-04 08:17 UTC, Halama commented
To bych teda asi udělal nějak jinak aby to šlo spustit v tom kontejneru.

2018-05-04 09:02 UTC, Halama commented
Zkouším takovouhle variantu `./tests/generate-ssh-keys.sh`:
```
#!/usr/bin/env bash


PRIVATE_KEY_FILE="/tmp/ssh.key"
PUBLIC_KEY_FILE="/tmp/ssh.key.pub"
rm -f ${PRIVATE_KEY_FILE}
rm -f ${PUBLIC_KEY_FILE}

ssh-keygen -b 4096 -t rsa -f ${PRIVATE_KEY_FILE} -q -N ''

PRIVATE_KEY=$(cat ${PRIVATE_KEY_FILE})

echo "export SSH_KEY_PRIVATE=\"$PRIVATE_KEY\""
echo "export SSH_KEY_PUBLIC=\"$(cat ${PUBLIC_KEY_FILE})\""
```
a pak zavoláš `eval $(docker run --rm -it -v $(pwd):/code keboola/db-writer-common ./tests/generate-ssh-keys.sh)`
Bohužel to nefunguje ale :)

Pokud ale udělám tohle tak to vypadá že to jede:
```
docker run --rm -it -v $(pwd):/code keboola/db-writer-common ./tests/generate-ssh-keys.sh > set.env
source ./set.env
``

2018-05-04 09:11 UTC, Halama commented on .travis.yml
> +  - docker-compose run tests
Na travisu mi to teda pořád nechce failnout https://travis-ci.org/keboola/db-writer-mssql/builds/374776772 pořád si ale myslím že je to náhoda. Lokálně mi to failuje běžně.

2018-05-04 09:15 UTC, MiroCillik commented
To s tym generovanim si vymyslel dobre. A ten wait este doriesime.

On Fri, 4 May 2018 11:11 Martin Halamíček, <notifications@github.com> wrote:

> *@Halama* commented on this pull request.
> ------------------------------
>
> In .travis.yml
> <https://github.com/keboola/db-writer-mssql/pull/22#discussion_r186027107>
> :
>
> >
>  script:
> -  - docker-compose run --rm tests
> +  - docker-compose run wait
> +  - docker-compose run tests
>
> Na travisu mi to teda pořád nechce failnout
> https://travis-ci.org/keboola/db-writer-mssql/builds/374776772 pořád si
> ale myslím že je to náhoda. Lokálně mi to failuje běžně.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/keboola/db-writer-mssql/pull/22#discussion_r186027107>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABa0jzBhM_7bXG6zPP0e-BKY2UC8paY0ks5tvBs7gaJpZM4Tw-uY>
> .
>

2018-05-04 12:13 UTC, tomasfejfar commented
Zkusil jsem to upravit tak, že by byl ten wait součástí build procesu toho wait kontejneru. Bohužel to nefunguje. Build proběhne vždycky úplně nejdřív, takže dřív než se spustí ten mssql kontejner, takže by se to nikdy nedočkalo. Takže takhle to fakt bohužel nepůjde :'(

Objevil jsem nicméně spoustu zajímavých věcí:
Pokud je někde potřeba provést vždycky něco bez cache v buildu, dá se použí cachebuster:
`ADD http://tycho.usno.navy.mil/cgi-bin/time.pl /tmp/bustcache`

To ve spojitosti s `docker-compose up --force-recreate app` zaruší, že se sice většina použije z cache, ale všechno co je za cachebusterem se provede znovu bez cache. 

Takže to vrátím zpátky na ten normální wait.

2018-05-04 12:30 UTC, Halama commented
tohle ` http://tycho.usno.navy.mil/cgi-bin/time.pl` mi nepřijde moc bezpečný stahovat něco z neznámý URL a ještě k tomu bez https.

Ten build s tím wait jak si to udělal teď mi příjde úplně cajk. 
Tuhle podivnost https://github.com/keboola/db-writer-mssql/blob/b3ade828376a652aea237340309825454af62e27/.travis.yml#L9 by pak mělo jít vyřešit nějak jak jsem se pokoušel tady https://github.com/keboola/db-writer-mssql/pull/22#issuecomment-386543603

2018-05-04 12:36 UTC, tomasfejfar commented
Jo vypadá to dobře. Vrátil jsem to tedy do původního stavu bez těch mých pokusů.

2018-05-09 08:45 UTC, MiroCillik commented
Ok, dakujem vsetkym za prispevky, mergnem to zatial takto :)
To generovanie klucov by som pripadne v dalsom PR nahradil tym, co navrhuje Martin:
```
docker run --rm -it -v $(pwd):/code keboola/db-writer-common ./tests/generate-ssh-keys.sh > set.env
source ./set.env
```

2018-05-09 08:46 UTC, MiroCillik commented on tests/phpunit/Writer/MSSQLTest.php
>          if (!is_dir('/data')) {
Ono je to trosku inac, ako sa zda na prvy pohlad, ale vyhodil som ten `if (!is_dir('/data')) { ... }`

2018-05-09 08:52 UTC, merged