escape special chars in bcp command
keboola/db-writer-mssql pull request #57
Opened 2020-01-28 14:58 UTC by ondrajodas

Solving - https://keboola.atlassian.net/browse/COM-114

2020-01-29 08:18 UTC, tomasfejfar requested changes
Mělo by se to přepsat na Symfony\Process pole, jak jsem psal.

2020-01-29 09:00 UTC, ondrajodas commented
chtěl jsem, ale jakmile je v tom dotazu `"` tak to neprojde:
```
'bcp' '[stage_5e31495020eff_simple]' 'in' '/tmp/simple.csvtPM8b2' '-f' '/tmpformat_file_stage_5e31495020eff_simple_5e31495028020' '-S' 'mssql,1433' '-U' 'sa' '-P' 'yourStrong(!)Password' '-d' 'test' '-k' '-F2' '-b50000' '-e\"/tmp/wr-db-mssql-errors\"' '-m1'
```
výstup je:
```
1) Keboola\DbWriter\Tests\Writer\MSSQLTest::testWriteMssql
Keboola\DbWriter\Exception\UserException: Import process failed. Output: SQLState = S1000, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server]Unable to open BCP error-file
```

2020-01-29 09:43 UTC, tomasfejfar commented
Přišlo mi to divné, tak jsem to zkusil přepsat a funguje to. Tak nevím, jak jsi to dělal. Nejspíš si v tom návu souboru nechal uvozovky nebo tak něco.

2020-01-29 09:44 UTC, ondrajodas commented
jj já jsem tam nechal ten command jak byl:
`sprintf('-e"%s"', $this->errorFile),`

2020-01-29 09:55 UTC, tomasfejfar commented
Takže ti to oescapovalo ty uvozovky a tys tím pádem chtěl error file `/var/log/"somefile"` nebo možná dokonce `/var/log/\"somefile\"` :)

2020-01-29 09:57 UTC, tomasfejfar commented
Akorát failnul build na unused method. Tak znova ;)

2020-01-29 10:13 UTC, ondrajodas commented
jo jasně, on to ještě oescapuje.... a jak bych to měl udělat u extractoru kde je podobný problém s heslem když tam se do BCP vola advenced query kde je třeba `select * from "special"`?

2020-01-29 10:27 UTC, tomasfejfar commented
No, tam chceš ty uvozovky oescapované, tam je to správně, ne? Prostě jde o to, že do toho pole prostě pošleš tu hodnotu tak jak ji chceš. A ono se to postará o to, aby se dostala tak jak jsi ji dal v tom poli do toho programu.

2020-01-29 10:29 UTC, tomasfejfar approved these changes
Jediná nevýhoda téhle verze je, že si nemůžeš vytahnout ten přesný command (a vypadne jen JSON pole těch parametrů v poli), co si to tahá. Ale na druhou stranu zas máme jistotu, že tam není prostor pro "exec injection" :) Reviewni to prosím po mě. 

Ten escape zmizel, protože na tom spadnul PhpStan

2020-01-29 10:46 UTC, ondrajodas commented
> No, tam chceš ty uvozovky oescapované, tam je to správně, ne? Prostě jde o to, že do toho pole prostě pošleš tu hodnotu tak jak ji chceš. A ono se to postará o to, aby se dostala tak jak jsi ji dal v tom poli do toho programu.

tam to právě zařve taky, ale to dyžtak bychom pořešili v PR u extractoru

2020-01-29 10:51 UTC, ondrajodas commented
takhle teda ok... zkoušel jsem i hesla se speciálníma znakama a projde v pohodě

2020-01-29 11:10 UTC, merged

2020-01-29 21:33 UTC, michal-keboola commented
Zdravim, panove. Pristal na Zendesku nasledujici dotaz:

In the latest update to the writer we are now having an issue with our table name saying it isn't valid. 'PurchaseOrder-Line'. This wasn't an issue up until last night, can I assume this is an error or will it be this way going forward.
No real business impact as we will change this to load to a separate table with an underscore instead but am keen to know if a dash will be supported again in future or not.

Submitting from the errored configuration as I will change the config in the live one. Errored job here
https://connection.keboola.com/admin/projects/2816/jobs/568406878

Jelikoz tohle je posledni update komponenty, tak se bojim, ze by to mohlo byt spojene.

Zendesk TIcket: https://keboola.zendesk.com/agent/tickets/12726

2020-01-30 08:49 UTC, tomasfejfar commented
Koukám na to a asi vidím i chybu.

2020-01-30 08:49 UTC, tomasfejfar commented
hned pošlu fix